### PR TITLE
Continuum fitting GUI fix, doc changes

### PR DESCRIPTION
**Pull request by nhmc**
This fixes the continuum fitting GUI, updates the notebooks again, and fixes the linelist documentation.

Sorry for lumping so many changes into one PR!

### CODE REVIEW

**Comment by ntejos** [comment]
BTW Neil, what happened with the capability of adding a break (i.e. discontinuity) in the continuum fitting GUI?

**Comment by nhmc** [comment]
You should be able to just add a few knots close together and it will approximate a break. The ability to add a discontinuity was originally there because putting knots too close together using standard cubic splines resulting in 'ringing'. But Akima splines don't have than problem, so I took it out.

**Comment by nhmc** [comment]
Merging.

**Comment by ntejos** [comment]
I see, thanks for the clarification.

**Pull request merged**
