### PR TITLE
Refactor PyQt5 -> PySide2

### PR DESCRIPTION
**Pull request by finagle29**
PySide2 has a more permissive license (LGPL 3) than PyQt5 (GPL 3), and practically the same public API.

### CODE REVIEW

**Comment by finagle29** [comment]
Tests pass locally
`=========== 238 passed, 1 skipped, 233 warnings in 155.40s (0:02:35) ===========`

**Review by profxj — APPROVED** [review]
Thanks a bunch @finagle29 !

**Comment by finagle29** [comment]
I'm going to do the same for PypeIt and then merge both PRs at the same time.

**Comment by finagle29** [comment]
tagging pypeit/pypeit#1072

**Comment by finagle29** [comment]
merging!

**Comment by finagle29** [comment]
@profxj could you merge this?

**Comment by profxj** [comment]
merging!

**Pull request merged**
