### PR TITLE
AbsSystem/DLASystem: from_components

### PR DESCRIPTION
**Pull request by profxj**
Puts a 'hook' into AbsSystem specific to DLASystem
which comes from pyigm.

Doesn't generate a dependence of pyigm for linetools,
but is not an elegant approach.  Might be a first
step towards pushing AbsSystem into pyigm..

### CODE REVIEW

**Comment by nhmc** [comment]
Why make this DLA-specific?  Instead of checking the class name, it seems better to just check whether any component has Zion = (1,1).

**Comment by profxj** [comment]
Have made the NHI call generic.

**Comment by nhmc** [comment]
Looks good to me. Please merge when the tests pass.

**Comment by nhmc** [comment]
Merging.

**Pull request merged**
