### PR TITLE
 LineList: Making subset_lines() to return a LineList object instead.

### PR DESCRIPTION
**Pull request by ntejos**
LineList: Making subset_lines() to return a LineList object instead.

Initial commit; will use Travis to check up crashes from tests and will fix them one at a time.

### CODE REVIEW

**Comment by ntejos** [comment]
The current failure seems to do with copy.copy() in python 3, but seems to be working fine in python 2.7 ... any thoughts?

**Comment by nhmc** [comment]
I have a fix - I will merge this and then apply it.

**Comment by nhmc** [comment]
Actually, I can't merge because there are conflicts. Could you resolve the conflicts, and then apply the changes in the attached diff?

[diff.txt](https://github.com/linetools/linetools/files/107620/diff.txt)

**Comment by ntejos** [comment]
Sure, will do.

**Comment by nhmc** [comment]
Thanks. Merging.

**Pull request merged**
