### PR TITLE
Updates to AbsSystem

### PR DESCRIPTION
**Pull request by profxj**
Minor updates:

- I/O
- nsig for measure_ew

No new tests or docs

### CODE REVIEW

**Comment by astronomeara** [comment]
Seems sensible.  Why 3 sig vs 2?

**Comment by profxj** [comment]
I don't trust our error estimates  ;)

**Comment by astronomeara** [comment]
Even more sensible :)  Thumbs up from me.

**Comment by profxj** [comment]
Merging.

**Pull request merged**
