### PR TITLE
minor tweaks for speed up in abssystem

### PR DESCRIPTION
**Pull request by ntejos**
As stated...

### CODE REVIEW

**Comment by profxj** [comment]
Can you keep c_mks as originally defined (I believe we use
it this way throughout linetools) and just add a new global, 
e.g.  c_mks_value ?

**Comment by ntejos** [comment]
Let me check what was the previous convention. I thought that it was `c_mks` as a float number in MKS units...

**Comment by ntejos** [comment]
It seems that this is the only file within linetools where we have used this variable. The only other time that we have used it (that I recall) was in IGMGuesses, and the convention was the one I just adopted in this PR. Given that the name already include the unit system (i.e. MKS), it does not make much sense to have it as a `Quantity`...

**Comment by profxj** [comment]
ok, check and merge.

**Pull request merged**
